---
- name: add apt_key file
  apt_key: >
    id="{{ nodejs_apt_key_id }}"
    url="{{ nodejs_apt_key_url }}"
    state=present

- name: add apt_repository
  apt_repository: >
    repo="{{ nodejs_repo }}"
    state=present
    validate_certs="{{ nodejs_repo_validate_certs }}"

- name: install apt package
  apt: >
    name="{{ item }}"
    state=present
    update_cache="{{ nodejs_update_cache|default(omit) }}"
    cache_valid_time="{{ nodejs_cache_valid_time|default(omit) }}"
  with_items:
    - "{{ nodejs_package_list }}"
